const Actions = {
  SET_EDITOR_TEXT: "SET_EDITOR_INTIAL_VALUE",
  RESET_EDITOR: "RESET_EDITOR_INITIAL_STATE",
  SET_BLOG_DETAILS: "SET_UPDATE_BLOG_DETAILS",
  SET_BLOG_TITLE: "SET_BLOG_TITLE"
};

export default Actions;
